[package]
name = "solidity-function-equiv-cost"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "0.6.2"
eyre = "0.6.7"
itertools = "0.10.3"
